train: ../train/images
val: ../valid/images
test: ../test/images

nc: 5
names: ['boat', 'buoy', 'jetski', 'life_saving_appliances', 'swimmer']

roboflow:
  workspace: ntnu-2wibj
  project: seadronessee-odv2
  version: 11
  license: CC BY 4.0
  url: https://universe.roboflow.com/ntnu-2wibj/seadronessee-odv2/dataset/11